/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Datos.Campos;
import Logica.CreadorTabla;
import Logica.InicializadorArchivo;
import Logica.GestorArchivo;
import static Logica.GestorArchivo.LongitudesCampos;
import Logica.GestorRegistro;
import Patrones.TemplateSerializar;
import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 Programacion 3
 Realizado por: Juan Cobos, Adrian Flores, Edgar Mora
 * 
 */
public class RecuperarDatos extends javax.swing.JFrame {

    private static String PATH_ARCHIVO = "archivos/META_BD.csv";
    public String histo=null;
    /**
     * Creates new form RecuperarDatos
     */
    public RecuperarDatos() {
        initComponents();
        setLocationRelativeTo(null);
        fondoPane();
    }
    
    private void showVentanaPrincipal() throws IOException {
        Principal ventana = new Principal();
        ventana.setVisible(true);
        ventana.setHistorial(histo);
    }
    public void fondoPane(){
        UIManager UI=new UIManager();
        UI.put("OptionPane.background", Color.gray);
        UI.put("Panel.background", Color.gray);
        UI.put("OptionPane.messageForeground", Color.white);
    }
    public String recuperarHist()throws FileNotFoundException, IOException, ClassNotFoundException{
        String histor="";
        try (ObjectInputStream input_hist = new ObjectInputStream(new FileInputStream("serializar/Principal_Historial.dat"))) {
            histo=(String)input_hist.readObject();
            input_hist.close();
        }catch(IOException x){
            
        }
        return histor;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bAceptar = new javax.swing.JButton();
        bNuevos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Recuperar Datos");
        setBackground(new java.awt.Color(0, 0, 51));
        setLocationByPlatform(true);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Imprint MT Shadow", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(" BASE DE DATOS - BIENVENIDOS");
        jLabel3.setFocusable(false);
        jLabel3.setRequestFocusEnabled(false);
        jLabel3.setVerifyInputWhenFocusTarget(false);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Imprint MT Shadow", 1, 18)); // NOI18N
        jLabel1.setText("           RECUPERAR DATOS");
        jLabel1.setFocusable(false);

        bAceptar.setBackground(new java.awt.Color(204, 204, 204));
        bAceptar.setText("Aceptar");
        bAceptar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });

        bNuevos.setBackground(new java.awt.Color(204, 204, 204));
        bNuevos.setText("Nuevo");
        bNuevos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bNuevos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNuevosActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fond.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(bAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(bNuevos, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bNuevos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
        
        try {
            
            if ( InicializadorArchivo.recuperarDatos(PATH_ARCHIVO) ) {
                    //            GestorArchivo.desSerializarGestorArchivo();
                //CreadorTabla.DesSerializar_CreadorTabla();\
                    //           GestorRegistro.deserializar_GestorRegistro();
                TemplateSerializar cargar = new GestorArchivo();
                cargar.Deserializar();
                //CreadorTabla.DesSerializar_CreadorTabla();
                histo=recuperarHist();
                JOptionPane.showMessageDialog(null, "Se ha recuperado los datos");
                
            } else {
                JOptionPane.showMessageDialog(null, "Se ha creado un nuevo archivo");
            }
            this.dispose();
            showVentanaPrincipal();
        } catch (IOException ex) {
            Logger.getLogger(RecuperarDatos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RecuperarDatos.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }//GEN-LAST:event_bAceptarActionPerformed

    private void bNuevosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNuevosActionPerformed
        
        try {
            this.dispose();
            if ( InicializadorArchivo.sobreescribirDatos(PATH_ARCHIVO) ) {
                histo=null;
                JOptionPane.showMessageDialog(null, "Se ha sobreescrito el archivo anterior", null, JOptionPane.PLAIN_MESSAGE);          
            } else {
                histo=null;
                JOptionPane.showMessageDialog(null, "Se ha creado un nuevo archivo", null, JOptionPane.PLAIN_MESSAGE);   
            }
            showVentanaPrincipal();
        } catch (IOException ex) {
            Logger.getLogger(RecuperarDatos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bNuevosActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptar;
    private javax.swing.JButton bNuevos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
